### ISSUE TITLE
Error in post-command-hook (flyspell-post-command-hook): (void-function find-function-library)

### ISSUE THREAD

**Issue by rafoo** [tmalsburg/guess-language.el#10]
I get the following error message:

Error in post-command-hook (flyspell-post-command-hook): (void-function find-function-library)

From the beggining of `guess-language.el`, I assume that the function `find-function-library` should be found in `find-func` but no such function is present there in my case. However a function `find-library` is present.

**Comment by tmalsburg** [comment]
To my knowledge `find-function-library` has been part of Emacs for many years.  I think this is a problem with your install.  I could change to `find-library-name` if that helps but `find-library` is not doing what we want.

**Comment by rafoo** [comment]
Thank you for the explanation.

`find-function-library` is in Emacs since release 24.5 : https://github.com/emacs-mirror/emacs/commit/6d14e0d361cfb3589874fe1b559e30b4fd3eb284

I am using the Debian Stable (Jessie) version of Emacs, which is Emacs 24.4.1. This version has `find-library-name` however.

**Comment by tmalsburg** [comment]
Pushed a fix: 85cfda48487483e3fb217d04bd854006e944189a  Please let me know whether that's working for you.

**Comment by rafoo** [comment]
It works! Thank you very much!!
