### ISSUE TITLE
"Undefined dictionary: en" when commiting with magit

### ISSUE THREAD

**Issue by DamienCassou** [tmalsburg/guess-language.el#15]
Hi,

when I create a commit from magit, I get:

    Error in post-command-hook (flyspell-post-command-hook): (error "Undefined dictionary: en")

**Comment by DamienCassou** [comment]
guess-language doesn't produce the same error in other buffers.

**Comment by tmalsburg** [comment]
Have a look at section [language settings in the documentation](https://github.com/tmalsburg/guess-language.el#language-settings).

**Comment by tmalsburg** [comment]
I'm assuming this is fixed.  Feel free to reopen if not.
