### ISSUE TITLE
"advice" dependency not found

### ISSUE THREAD

**Issue by wedens** [tmalsburg/guess-language.el#22]
After some recent changes (d2a13303027e32ca33d05253f6d287c8c21ddd5f) guess-language depends on `advice 0.1` package which is not on melpa, and consequently guess-language fails to build.

**Comment by tmalsburg** [comment]
`advice.el` is part of Emacs.  I would have thought that MELPA understands this.  I also don't experience this problem on my system.  Could you please give me the precise error message?

**Comment by TimSoethout** [comment]
Same issue here:

```
Found 1 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: guess-language@dotfile... [1/1]
Package advice is unavailable. Is the package name misspelled?

An error occurred while installing guess-language (error: (error Package ‘advice-0.1’ is unavailable))

Error in dotspacemacs/user-config: Cannot open load file: No such file or directory, guess-language
```

I am using spacemacs, using Emacs Version 26.1 (9.0) on OSX

**Comment by tmalsburg** [comment]
What code is producing these messages?  Is this plain package.el or some configuration system (e.g., spacemacs).  I can of course remove the dependency but I think there's nothing wrong with it and the problem lies elsewhere.

**Comment by TimSoethout** [comment]
I used `dotspacemacs-additional-packages '(guess-language)`  and 
```  (require 'guess-language)
  (setq guess-language-languages '(en nl))
  (setq guess-language-min-paragraph-length 35)
```
 in `dotspacemacs/user-config`.

For now I commented all of this, and am not using `guess-language`.

**Comment by tmalsburg** [comment]
Hm. I removed the dependency for now as a stopgap solution.  It was suggested by an Emacs core developer but I don't fully understand this business.
