### ISSUE TITLE
guess-language fail to start

### ISSUE THREAD

**Issue by LevPetrovitch** [tmalsburg/guess-language.el#23]
When opening a text file, I get the following error

`Error in post-command-hook (flyspell-post-command-hook): (wrong-type-argument symbolp (quote typo-mode))`

Looking in the code I found a call `(bound-and-true-p 'typo-mode)` in the function  `guess-language-switch-typo-mode-function`.  Given that `bound-and-true-p` takes a **symbol** as argument this is obviously an error.

Removing the quote solves the problem for me

**Comment by tmalsburg** [comment]
Thank you for reporting this.  I previously used `boundp` instead and there it worked.

**Comment by LevPetrovitch** [comment]
You're welcome :)
I'd like to take the occasion to thank you for this package. As I frequently have documents (mainly org agenda files) written in a mix of Italian, English, and French, something like this package is way more than just useful :)

**Comment by tmalsburg** [comment]
Hey, glad to hear that you find this useful.  I mostly use two languages (German, English), but sometimes more, and it certainly saves me some keystrokes over the course of the day. :)
