### ISSUE TITLE
Advantage from using local variables ?

### ISSUE THREAD

**Issue by azzamsa** [tmalsburg/guess-language.el#24]
Maybe add 'advantage of using local variables' in readme ?

e.g 

```
;; Local Variables:
;; ispell-check-comments: exclusive
;; ispell-local-dictionary: "en"
```

```
%%% Local Variables:
%%% ispell-local-dictionary: "british"
%%% End:
```

**Comment by tmalsburg** [comment]
Hi. Could you please provide some context. I don't understand how this is relevant here.  The point of this package is that you don't have to manually select dictionaries.

**Comment by azzamsa** [comment]
> I write a lot of text in multiple languages

Same here, but I use different languages in different document.

> guesses the language of the current paragraph and then changes the dictionary of ispell

Oh my bad, the difference here is that it's for people that write various languages in "single" document. So this package changes ispell dictionary on the fly.

in my case, I write different language in different document, so I can use local variable to specify the dictionary in current document.

Btw. Great package. :)
