### ISSUE TITLE
Updating version for GNU ELPA archive required

### ISSUE THREAD

**Issue by dunmaksim** [tmalsburg/guess-language.el#39]
Hello!

Verison `0.0.1` of package `guess-language` in [GNU ELPA archive](https://elpa.gnu.org/devel/guess-language.html) is very old and have critical bug: recipe do not contain files from `trigrams/` directory.

When `guess-language-mode` is activated, Emacs show error message:

```text
Error in post-command-hook (flyspell-post-command-hook): (file-missing "Opening input file" "File or folder does not exists" "/home/dunaevsky/.emacs.d/elpa/guess-language-0.0.1/trigrams/en")
```

Please, update recipe for GNU ELPA archive.

**Comment by tmalsburg** [comment]
To be honest, I regret having submitted this package to ELPA.  I can't make changes myself there (despite having done the GNU paper work).  It's also not clear whether we need GNU paperwork from the contributors of the various languages tri-gram statistics.  I don't have time to deal with this stuff and I'm not a lawyer.  I strongly recommend installing from this git repository or through MELPA.
