### ISSUE TITLE
Esperanto in `guess-language-langcodes`

### ISSUE THREAD

**Issue by joostkremers** [tmalsburg/guess-language.el#40]
Hi, I just noticed that the entry for Esperanto in `guess-language-langcodes` reads:

    (eo     . ("eo"         "English" "🟩"   "Esperanto"))

This should of course be:

    (eo     . ("eo"         "Esperanto" "🟩"   "Esperanto"))

**Comment by tmalsburg** [comment]
Fixed in a17203d26135b970e4d7c5d101955d41303a758f. Thank you.
