### ISSUE TITLE
Missing trigrams after install of `gnu elpa` package

### ISSUE THREAD

**Issue by orontee** [tmalsburg/guess-language.el#44]
# Context

I am using GNU Emacs 30.0.60 and installed `guess-language.el` version 0.0.1 from `gnu elpa` package. When I call `guess-language` from a text buffer, the following error happens:
```
guess-language-compile-regexps: Opening input file: Aucun fichier ou dossier de ce type, /home/matthias/.config/emacs/elpa/guess-language-0.0.1/trigrams/en
```
Which is not surprising:
```
matthias@peitho:~$ tree .config/emacs/elpa/guess-language-0.0.1/
.config/emacs/elpa/guess-language-0.0.1/
├── guess-language-autoloads.el
├── guess-language.el
├── guess-language.elc
└── guess-language-pkg.el

1 directory, 4 files
```

No problem with version from `melpa`:
```
matthias@peitho:~$ ls -l .config/emacs/elpa/guess-language-20240528.1319/ | wc -l
73
```

**Comment by tmalsburg** [comment]
Hi, please just use MELPA.  The ELPA version is not up-to-date.  Since I don't have the necessary permissions, I can't update it.  Shouldn't have submitted to ELPA I'm afraid.

**Comment by m4lvin** [comment]
It took me a moment to find this. For anyone else coming here and also using `use-package` with multiple repositories configured and (for other/most packages) preferring `elpa` over `melpa`, this works for me:

```elisp
(setq package-archives '(("gnu"          . "https://elpa.gnu.org/packages/")
                         ("melpa-stable" . "https://stable.melpa.org/packages/")
                         ("melpa"        . "https://melpa.org/packages/")))
(setq package-archive-priorities '(("melpa-stable" . 10)
                                   ("gnu"          . 5)
                                   ("melpa"        . 0)))

(use-package guess-language
  :pin melpa)
```

PS: it seems the outdated/incomplete source for the elpa repo is here:
https://git.savannah.gnu.org/cgit/emacs/elpa.git/log/?h=externals/guess-language
Who would have the permissions to update / sync this again? Or to just remove the package from there?
