### ISSUE TITLE
validate-setq on guess-language-langcodes

### ISSUE THREAD

**Issue by manuel-uberti** [tmalsburg/guess-language.el#7]
Hi,

just upgraded `guess-language` from MELPA. I have this snippet in my init file:
```emacs-lisp
(use-package guess-language         ; Automatically detect language for Flyspell
  :ensure t
  :defer t
  :init (add-hook 'text-mode-hook #'guess-language-mode)
  :config
  (validate-setq guess-language-langcodes '((en . ("en_GB" "English"))
                                            (it . ("it_IT" "Italian")))
                 guess-language-languages '(en it)
                 guess-language-min-paragraph-length 45)
  :diminish guess-language-mode)
```
I get this warning upon restarting Emacs:
```
Error (use-package): guess-language :config: Looking for `(alist :key-type symbol :value-type ...)' in `((en "en_GB" "English") (it "it_IT" "Italian"))' failed because:
Looking for `(repeat (cons symbol list))' in `((en "en_GB" "English") (it "it_IT" "Italian"))' failed because:
Looking for `(cons symbol list)' in `(en "en_GB" "English")' failed because:
Looking for `list' in `("en_GB" "English")' failed because:
  wrong number of elements
```
I am using `validate-setq` from @Malabarba's [validate](https://github.com/Malabarba/validate.el) to be sure I am setting the right values everywhere in my init file.

Everything's working fine with regular `setq`, so this is might not be related to your package.

**Comment by tmalsburg** [comment]
I'm not familiar with validate but as far as I can see it complains that `("en_GB" "English")` is not a list which is incorrect.  Is it possible that validate is confused?

**Comment by manuel-uberti** [comment]
Could be, but we need @Malabarba to help us here.

**Comment by Malabarba** [comment]
Yes, looks like a bug in validate.el. I'll have to check it out.

**Comment by manuel-uberti** [comment]
Thank you!
I'll close this issue, then, since it is not related to `guess-language`.

**Comment by manuel-uberti** [comment]
@Malabarba did you have a chance to have a look at this?

**Comment by Malabarba** [comment]
No, but I'll try to over the weekend. Feel free to ping me if I forget. :-)

**Comment by manuel-uberti** [comment]
Ok, latest commit by @Malabarba on validate.el fixed this. Thanks!

**Comment by tmalsburg** [comment]
Great and thanks for your effort @Malabarba and @manuel-uberti.
