### ISSUE TITLE
Dutch ?

### ISSUE THREAD

**Issue by HilleniusGijs** [tmalsburg/guess-language.el#9]
The table of languages that are currently supported by guess-language-mode mentions:
Dutch	nl	de 

Should that not be Dutch nl nl_NL?

**Comment by tmalsburg** [comment]
Fixed, thanks.

**Comment by tmalsburg** [comment]
By the way, on my system it's `Dutch nl nederlands`.  We need a way to guess the correct name of the dictionary.  It's a shame that ispell/aspell/flyspell don't use standard names.

**Comment by rien333** [comment]
So the fact I had to change "nederlands" to "dutch" in the following statement in `guess-language.el` is not really a bug, but rather the consequence of stuff not being normalized all to well?

```lisp
(defcustom guess-language-langcodes
  '((ar . ("ar"         nil))
    (cs . ("czech"      "Czech"))
    (da . ("dansk"      nil))
    ...
    (nl . ("nederlands" nil)) # changed this to dutch to work
    ...
    (sv . ("svenska"    nil)))
  "Language codes for spell-checker and typo-mode.

**Comment by tmalsburg** [comment]
Different spell-checkers apparently use different names for their dictionaries.  Not sure where there is a clean way to deal with this automatically.
